# -*- coding: utf-8 -*-
"""denseNet121.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M32bDaFisOjrGRuAudBRPLJj8lLx2Xg7
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.applications.densenet import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
import numpy as np

train_dir = '/content/drive/MyDrive/dataset/train'

datagen = ImageDataGenerator(
    rescale=1./255,
    preprocessing_function=preprocess_input,  # DenseNet için preprocessing
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

generator = datagen.flow_from_directory(
    train_dir,
    target_size=(150, 150),  # Görselleri 150x150 boyutuna getirecek
    batch_size=32,
    class_mode='categorical',  # Çok sınıflı sınıflandırma
    shuffle=False
)

X = []
y = []

# Veri dizilerini doldurma
for i in range(len(generator)):
    imgs, labels = generator[i]
    X.extend(imgs)
    y.extend(labels)

X = np.array(X)
y = np.array(y)

kf = KFold(n_splits=5, shuffle=True, random_state=42)
fold = 1

for train_index, val_index in kf.split(X):
    X_train, X_val = X[train_index], X[val_index]
    y_train, y_val = y[train_index], y[val_index]

    # DenseNet121 modelini yükle
    base_model = DenseNet121(weights='imagenet', include_top=False, input_shape=(150, 150, 3))
    base_model.trainable = False  # Transfer öğrenme için base modelin katmanlarını eğitmeyeceğiz

    # Modeli oluşturma
    num_classes = len(generator.class_indices)  # Sınıf sayısını otomatik olarak alıyoruz
    model = Sequential([
        base_model,
        Flatten(),
        Dense(512, activation='relu'),
        Dropout(0.5),
        Dense(num_classes, activation='softmax')  # Çok sınıflı çıkış için softmax
    ])

    # Modeli derleme
    model.compile(
        loss='categorical_crossentropy',  # Çok sınıflı kayıp fonksiyonu
        optimizer='adam',  # Optimizasyon algoritması
        metrics=['accuracy']  # Başarı metriği
    )

    # Modeli eğitim
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=35,
        verbose=1
    )

plt.figure()
plt.plot(history.history['accuracy'], color='blue', label='Train Accuracy')
plt.plot(history.history['val_accuracy'], color='green', label='Validation Accuracy')
plt.title(f' Accuracy Comparison')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()
print(f'💙💚 Bu grafik Fold {fold} için eğitim ve doğrulama doğruluğunu karşılaştırıyor.')

    # Eğitim kaybı ve doğrulama kaybını karşılaştıran grafik
plt.figure()
plt.plot(history.history['loss'], color='red', label='Train Loss')
plt.plot(history.history['val_loss'], color='orange', label='Validation Loss')
plt.title(f' Loss Comparison')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()
print(f'❤️🧡 Bu grafik Fold {fold} için eğitim ve doğrulama kaybını karşılaştırıyor.')

fold += 1