# -*- coding: utf-8 -*-
"""EfficientnetTransfer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1afCbVmsovNSOjYRd9S8AoqIPnVttU1zp
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip -o -q "/content/drive/MyDrive/Dataset-1.zip" -d /content/

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

train_dir = '/content/Dataset-1/train'
val_dir = '/content/Dataset-1/val'
test_dir = '/content/Dataset-1/test'

datagen = ImageDataGenerator(rescale=1./255)

train_gen = datagen.flow_from_directory(train_dir, target_size=(224, 224), batch_size=32, class_mode='categorical')
val_gen = datagen.flow_from_directory(val_dir, target_size=(224, 224), batch_size=32, class_mode='categorical')
test_gen = datagen.flow_from_directory(test_dir, target_size=(224, 224), batch_size=32, class_mode='categorical', shuffle=False)

base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
for layer in base_model.layers:
    layer.trainable = False  # Bütün katmanlar dondu

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
output = Dense(train_gen.num_classes, activation='softmax')(x)

model_effnet = Model(inputs=base_model.input, outputs=output)

model_effnet.compile(optimizer=Adam(learning_rate=1e-4), loss='categorical_crossentropy', metrics=['accuracy'])

history_effnet_tl = model_effnet.fit(
    train_gen,
    validation_data=val_gen,
    epochs=35
)

y_probs_eff = model_effnet.predict(test_gen)
y_pred_eff = np.argmax(y_probs_eff, axis=1)
y_true = test_gen.classes
labels = list(test_gen.class_indices.keys())

print("📊 EfficientNetB0 Transfer Learning Sonuçları:")
print(classification_report(y_true, y_pred_eff, target_names=labels))

cm = confusion_matrix(y_true, y_pred_eff)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Purples', xticklabels=labels, yticklabels=labels)
plt.title("EfficientNetB0 – Confusion Matrix (Transfer Learning)")
plt.xlabel("Tahmin")
plt.ylabel("Gerçek")
plt.show()

acc = history_effnet_tl.history['accuracy']
val_acc = history_effnet_tl.history['val_accuracy']
loss = history_effnet_tl.history['loss']
val_loss = history_effnet_tl.history['val_loss']
epochs_range = range(len(acc))

plt.figure(figsize=(8, 5))
plt.plot(epochs_range, acc, label='Train Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.title('EfficientNetB0 - Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(epochs_range, loss, label='Train Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.title('EfficientNetB0 - Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()