// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDurbfTiJDBS9B9bPOKKcVFMzs7YK4fP9o',
    appId: '1:284769764287:web:8ad110c6682dc826b0970a',
    messagingSenderId: '284769764287',
    projectId: 'tarlatakipapp',
    authDomain: 'tarlatakipapp.firebaseapp.com',
    storageBucket: 'tarlatakipapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOCReHNw1VaheNEaFCInyRYrMZ0g4Tokg',
    appId: '1:284769764287:android:27daf4ef6ac837b8b0970a',
    messagingSenderId: '284769764287',
    projectId: 'tarlatakipapp',
    storageBucket: 'tarlatakipapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPMUOjZRRHxlexvB5Yt_WeRBRwMH6OCiA',
    appId: '1:284769764287:ios:28ac62d94c3ee748b0970a',
    messagingSenderId: '284769764287',
    projectId: 'tarlatakipapp',
    storageBucket: 'tarlatakipapp.firebasestorage.app',
    iosBundleId: 'com.example.tarlatakipapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPMUOjZRRHxlexvB5Yt_WeRBRwMH6OCiA',
    appId: '1:284769764287:ios:28ac62d94c3ee748b0970a',
    messagingSenderId: '284769764287',
    projectId: 'tarlatakipapp',
    storageBucket: 'tarlatakipapp.firebasestorage.app',
    iosBundleId: 'com.example.tarlatakipapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDurbfTiJDBS9B9bPOKKcVFMzs7YK4fP9o',
    appId: '1:284769764287:web:9b4ac1c0b0d3f0c1b0970a',
    messagingSenderId: '284769764287',
    projectId: 'tarlatakipapp',
    authDomain: 'tarlatakipapp.firebaseapp.com',
    storageBucket: 'tarlatakipapp.firebasestorage.app',
  );

}